baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
publishDir = "src/public"

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false
defaultContentLanguage = "en"
[languages]
  [languages.es]
    languageName = "es"
    title = "El blog de migtarx"
    subtitle = "Las aventuras del chico tech"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar mas"
    writtenBy = "Escrito por"
    readMore = "Leer mas"
    readOtherPosts = "Leer otros articulos"
    newerPosts = "Articulos nuevos"
    olderPosts = "Articulos anteriores"
    minuteReadingTime = "tiempo de lectura"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"
    [languages.es.params.logo]
      logoText = "migtarx"
      logoHomeLink = "/es"
    [languages.es.menu]
  [languages.en]
   languageName = "en"
    title = "migtarx blog"
    subtitle = "the adventures of a tech guy"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    [languages.en.params.logo]
      logoText = "migtarx"
      logoHomeLink = "/"
    [languages.en.menu]
